Home work 4
FiodarKarnilovich/educational_project pull request #5
Opened 2023-03-05 16:17 UTC by FiodarKarnilovich

AuthFilter  пока без Логата

2023-03-05 18:00 UTC, anarut requested changes

2023-03-05 18:00 UTC, anarut commented on web/pom.xml
> +            <version>6.0.0</version>
put this version into parent properties

2023-03-05 18:00 UTC, anarut commented on web/src/main/java/by/karnilovich/web/servlet/UserRegistrationServlet.java
> +        resp.sendRedirect("/web/jsp/index_logged.jsp");
usually registration process is not the same as login process. I think after successful registration you redirect to login page to proceed with it.

2023-03-05 18:00 UTC, anarut commented on web/src/main/java/by/karnilovich/web/servlet/AuthFilter.java
> +            if (requestURI.equals("/web/jsp/index.jsp") || requestURI.equals("/web/jsp/contacts.jsp") ||
all Strings in this file would be great to put into java constants

2023-03-05 18:00 UTC, anarut commented on web/src/main/java/by/karnilovich/web/servlet/AuthFilter.java
> +                LOGGER.debug(" 1 if -  "+requestURI);
put more effort and leave valuable comments. E.g. 
LOGGER.debug("Authentication is not required for :  " + requestURI + ";");
or
LOGGER.debug("Authentication required for :  " + requestURI + ";");
some code
LOGGER.debug("User 'john doe' is not authenticated. Redirecting to login page");

2023-03-05 18:00 UTC, anarut commented on web/src/main/java/by/karnilovich/web/servlet/AuthFilter.java
> +            } else if ((requestURI.equals("/web/jsp/index_logged.jsp") || requestURI.equals("/web/jsp/view_user_details.jsp")
You don't need to have this list of URIs. It's enough to have list of URIs w/o auth. All other URIs require auth.

2023-03-05 18:00 UTC, anarut commented on web/src/main/java/by/karnilovich/web/servlet/AuthFilter.java
> +                } else if (requestURI.equals("/web/logout")) {
should not be here. auth is not responsible for it (Logout servlet is)

2023-03-05 18:00 UTC, anarut commented on web/src/main/java/by/karnilovich/web/servlet/LoginServlet.java
> +                writer.println("All right");
remove this line.

2023-03-05 18:00 UTC, anarut commented on web/src/main/java/by/karnilovich/web/servlet/NewServlet.java
> +//public class NewServlet extends HttpServlet {
remove this class if you don't need it

2023-03-05 18:07 UTC, FiodarKarnilovich commented on web/src/main/java/by/karnilovich/web/servlet/NewServlet.java
> +//public class NewServlet extends HttpServlet {
delete

2023-03-05 18:09 UTC, FiodarKarnilovich commented on web/pom.xml
> +            <version>6.0.0</version>
added dependancy

2023-03-05 18:17 UTC, FiodarKarnilovich commented on web/src/main/java/by/karnilovich/web/servlet/UserRegistrationServlet.java
> +        resp.sendRedirect("/web/jsp/index_logged.jsp");
сделал

2023-03-05 18:33 UTC, FiodarKarnilovich commented on web/src/main/java/by/karnilovich/web/servlet/AuthFilter.java
> +                LOGGER.debug(" 1 if -  "+requestURI);
пока частично

2023-03-05 18:35 UTC, FiodarKarnilovich commented on web/src/main/java/by/karnilovich/web/servlet/LoginServlet.java
> +                writer.println("All right");
удалил

2023-03-05 18:37 UTC, FiodarKarnilovich commented on web/src/main/java/by/karnilovich/web/servlet/AuthFilter.java
> +            if (requestURI.equals("/web/jsp/index.jsp") || requestURI.equals("/web/jsp/contacts.jsp") ||
сделал

2023-03-09 05:53 UTC, anarut approved these changes

2023-03-09 05:53 UTC, merged